configdefaults = {
    'MAX_POLYPHONY': {'type': 'range', 'min': 1, 'max': 128, 'default': 80},
    'MIDI_CHANNEL': {'type': 'range', 'min': 1, 'max': 16, 'default': 1},
    'CHANNELS': {'type': 'options', 'options': ['2', '4'], 'default': 0},
    'BUFFERSIZE': {'type': 'options',
                   'options': ['16', '32', '64', '128', '256', '512', '1024', '2048'], 'default': 3},
    'SAMPLERATE': {'type': 'options', 'options': ['44100', '48000', '96000'], 'default': 0},
    'GLOBAL_VOLUME': {'type': 'range', 'min': 0, 'max': 100, 'default': 100},
    'USE_BUTTONS': {'type': 'boolean', 'default': 'True'},
    'USE_HD44780_16X2_LCD': {'type': 'boolean', 'default': 'True'},
    'USE_HD44780_20x4_LCD': {'type': 'boolean', 'default': 'False'},
    'USE_I2C_7SEGMENTDISPLAY': {'type': 'boolean', 'default': 'False'},
    'USE_FREEVERB': {'type': 'boolean', 'default': 'False'},
    'USE_TONECONTROL': {'type': 'boolean', 'default': 'False'},
    'USE_SERIALPORT_MIDI': {'type': 'boolean', 'default': 'False'},
    'SAMPLES_DIR': {'type': 'string', 'default': './media'},
    'PRESET_BASE': {'type': 'int', 'default': 0},
    'AUDIO_DEVICE_NAME': {'type': 'options', 'options':[]},
    'SYSTEM_MODE': {'type': 'options', 'options': ['1', '2'], 'default': 0},
    'RAM_LIMIT_PERCENTAGE': {'type': 'range', 'min': 1, 'max': 95, 'default': 40},
    'BOXRELEASE': {'type': 'range', 'min': 1, 'max': 128, 'default': 30},
    'USE_GUI': {'type': 'boolean', 'default': 'False'},

    'PRINT_MIDI_MESSAGES': {'type': 'boolean', 'default': 'True'},
    'PRINT_LCD_MESSAGES': {'type': 'boolean', 'default': 'True'},

    'BUTTON_LEFT_MIDI': {'type': 'midi'},
    'BUTTON_RIGHT_MIDI': {'type': 'midi'},
    'BUTTON_ENTER_MIDI': {'type': 'midi'},
    'BUTTON_CANCEL_MIDI': {'type': 'midi'},
    'BUTTON_UP_MIDI': {'type': 'midi'},
    'BUTTON_DOWN_MIDI': {'type': 'midi'},
    'BUTTON_FUNC_MIDI': {'type': 'midi'},
    'BUTTON_LEFT_GPIO': {'type': 'int', 'default': 0},
    'BUTTON_RIGHT_GPIO': {'type': 'int', 'default': 0},
    'BUTTON_ENTER_GPIO': {'type': 'int', 'default': 0},
    'BUTTON_CANCEL_GPIO': {'type': 'int', 'default': 0},
    'BUTTON_UP_GPIO': {'type': 'int', 'default': 0},
    'BUTTON_DOWN_GPIO': {'type': 'int', 'default': 0},
    'BUTTON_FUNC_GPIO': {'type': 'int', 'default': 0},
    'GPIO_LCD_RS': {'type': 'int', 'default': 0},
    'GPIO_LCD_E': {'type': 'int', 'default': 0},
    'GPIO_LCD_D4': {'type': 'int', 'default': 0},
    'GPIO_LCD_D5': {'type': 'int', 'default': 0},
    'GPIO_LCD_D6': {'type': 'int', 'default': 0},
    'GPIO_LCD_D7': {'type': 'int', 'default': 0},
    'GPIO_7SEG': {'type': 'int', 'default': 0}

}
